"""
Cấu hình các nguồn theo dõi IR
"""

# Chỉ theo dõi tin trong N ngày gần nhất (áp dụng tự động cho mọi nguồn)
RECENT_DAYS = 7

CATEGORIES = {
    "bds": {"name": "Bất động sản", "emoji": "🏗️"},
    "finance": {"name": "Tài chính", "emoji": "💰"},
    "securities": {"name": "Chứng khoán", "emoji": "📈"},
    "bank": {"name": "Ngân hàng", "emoji": "🏦"},
    "other": {"name": "Khác", "emoji": "📋"},
}

SOURCES = [
    # ── Bất động sản ──────────────────────────────────────────────────────────
    {
        "id": "phatdat",
        "name": "Phát Đạt (PDR)",
        "emoji": "🏠",
        "category": "bds",
        "url": "https://www.phatdat.com.vn/ajax/reports/filter",
        "params": {"year": "", "quarter": "", "page": 1, "lang": "vi"},
        "source_page": "https://www.phatdat.com.vn/quan-he-nha-dau-tu#investor-2",
    },
    {
        "id": "vingroup",
        "name": "Vingroup",
        "emoji": "🏢",
        "category": "bds",
        "urls": [
            "https://vingroup.net/quan-he-co-dong/cong-bo-thong-tin/cong-bo-thong-tin",
            "https://vingroup.net/quan-he-co-dong/cong-bo-thong-tin/dai-hoi-dong-co-dong",
        ],
        "params": {"items": 50},
        "source_page": "https://vingroup.net/quan-he-co-dong/cong-bo-thong-tin",
    },
    {
        "id": "hoanghuy",
        "name": "Hoàng Huy",
        "emoji": "🏗️",
        "category": "bds",
        "url": "https://www.hoanghuy.vn/cong-bo-thong-tin/",
        "bctc_page": "https://www.hoanghuy.vn/bao-cao-tai-chinh/",
        "source_page": "https://www.hoanghuy.vn/cong-bo-thong-tin/",
    },
    {
        "id": "dic",
        "name": "DIG (DIC Corp)",
        "emoji": "🏘️",
        "category": "bds",
        "url": "https://www.dic.vn/cong-bo-thong-tin",
        "bctc_page": "https://www.dic.vn/bao-cao-tai-chinh",
        "source_page": "https://www.dic.vn/cong-bo-thong-tin",
    },
    {
        "id": "kdh",
        "name": "Khang Điền (KDH)",
        "emoji": "🏡",
        "category": "bds",
        "url": "https://www.khangdien.com.vn/co-dong/cong-bo-thong-tin",
        "bccb_page": "https://www.khangdien.com.vn/co-dong/bao-cao-cao-bach",
        "source_page": "https://www.khangdien.com.vn/co-dong/cong-bo-thong-tin",
    },
    {
        "id": "nvl",
        "name": "Novaland (NVL)",
        "emoji": "🌆",
        "category": "bds",
        "url": "https://www.novaland.com.vn/quan-he-dau-tu/cong-bo-thong-tin/thong-bao",
        "source_page": "https://www.novaland.com.vn/quan-he-dau-tu/cong-bo-thong-tin/thong-bao",
    },
    {
        "id": "nlg",
        "name": "Nam Long (NLG)",
        "emoji": "🏙️",
        "category": "bds",
        "url": "https://www.namlongvn.com/quan-he-nha-dau-tu/",
        "source_page": "https://www.namlongvn.com/quan-he-nha-dau-tu/#info-disclosure-section",
    },
    {
        "id": "vre",
        "name": "Vincom Retail (VRE)",
        "emoji": "🏬",
        "category": "bds",
        "url": "https://ir.vincom.com.vn/cong-bo-thong-tin/cong-bo-thong-tin-vi/",
        "source_page": "https://ir.vincom.com.vn/cong-bo-thong-tin/cong-bo-thong-tin-vi/",
    },
    {
        "id": "vhm",
        "name": "Vinhomes (VHM)",
        "emoji": "🏘️",
        "category": "bds",
        "url": "https://vinhomes.vn/vi/cong-bo-thong-tin",
        "source_page": "https://vinhomes.vn/vi/cong-bo-thong-tin",
    },
    {
        "id": "ksf",
        "name": "Sunshine (KSF)",
        "emoji": "☀️",
        "category": "bds",
        "url": "https://sunshinegroup.vn/cong-bo-thong-tin/",
        "api_url": "https://ir.sunshinegroup.vn/wp-json/api/v1/thong-tin-co-dong/cong-bo-thong-tin",
        "bctc_api_url": "https://ir.sunshinegroup.vn/wp-json/api/v1/thong-tin-co-dong/bao-cao-tai-chinh",
        "source_page": "https://sunshinegroup.vn/cong-bo-thong-tin/",
        "bctc_page": "https://sunshinegroup.vn/bao-cao-tai-chinh/",
    },
    # ── Tài chính ─────────────────────────────────────────────────────────────
    {
        "id": "f88",
        "name": "F88",
        "emoji": "💵",
        "category": "finance",
        "url": "https://nhadautu.f88.vn/cong-bo-thong-tin",
        "api_url": "https://apis.f88.vn/growth/f88vn/api/v1/Initial/InitPageInvestDocument",
        "bctc_api_url": "https://apis.f88.vn/growth/f88vn/api/v1/Initial/InitPageNewsSub",
        "source_page": "https://nhadautu.f88.vn/cong-bo-thong-tin",
        "bctc_page": "https://nhadautu.f88.vn/bao-cao-tai-chinh",
    },
    # ── Chứng khoán ───────────────────────────────────────────────────────────
    {
        "id": "vci",
        "name": "Vietcap (VCI)",
        "emoji": "📊",
        "category": "securities",
        "url": "https://www.vietcap.com.vn/quan-he-co-dong/",
        "bctc_page": "https://www.vietcap.com.vn/quan-he-co-dong/bao-cao-tai-chinh",
        "source_page": "https://www.vietcap.com.vn/quan-he-co-dong/",
    },
    {
        "id": "hds",
        "name": "HD Securities (HDS)",
        "emoji": "📉",
        "category": "securities",
        "url": "https://hdbs.vn/quan-he-co-dong/cong-bo-thong-tin/",
        "bctc_page": "https://hdbs.vn/quan-he-co-dong/bao-cao-tai-chinh/",
        "source_page": "https://hdbs.vn/quan-he-co-dong/cong-bo-thong-tin/",
    },
    {
        "id": "vck",
        "name": "VPS (VCK)",
        "emoji": "🧾",
        "category": "securities",
        "url": "https://www.vps.com.vn/quan-he-co-dong/cong-bo-thong-tin",
        "source_page": "https://www.vps.com.vn/quan-he-co-dong/cong-bo-thong-tin",
        "sections": [
            {"path": "cong-bo-thong-tin", "label": "CBTT"},
            {"path": "bao-cao-cong-ty", "label": "Báo cáo công ty"},
            {"path": "dai-hoi-dong-co-dong", "label": "ĐHĐCĐ"},
            {"path": "ho-so-doanh-nghiep", "label": "Hồ sơ DN"},
        ],
    },
    {
        "id": "tcx",
        "name": "TCBS (TCX)",
        "emoji": "🏛️",
        "category": "securities",
        "url": "https://www.tcbs.com.vn/nha-dau-tu/quan-he-nha-dau-tu/cong-bo-thong-tin/",
        "source_page": "https://www.tcbs.com.vn/nha-dau-tu/quan-he-nha-dau-tu/cong-bo-thong-tin/",
        "feeds": [
            {
                "url": "https://www.tcbs.com.vn/nha-dau-tu/quan-he-nha-dau-tu/cong-bo-thong-tin/",
                "label": "CBTT",
                "cbtt_only": True,
            },
            {
                "url": "https://www.tcbs.com.vn/nha-dau-tu/quan-he-nha-dau-tu/bao-cao-cong-ty/bao-cao-thuong-nien/",
                "label": "BCTN",
                "cbtt_only": False,
            },
            {
                "url": "https://www.tcbs.com.vn/nha-dau-tu/quan-he-nha-dau-tu/bao-cao-cong-ty/bao-cao-tinh-hinh-quan-tri-cong-ty/",
                "label": "BC quản trị",
                "cbtt_only": False,
            },
        ],
    },
    {
        "id": "mbs",
        "name": "MB Securities (MBS)",
        "emoji": "📑",
        "category": "securities",
        "url": "https://www.mbs.com.vn/cong-bo-thong-tin/",
        "bctc_page": "https://www.mbs.com.vn/bao-cao-tai-chinh/",
        "source_page": "https://www.mbs.com.vn/cong-bo-thong-tin/",
    },
    {
        "id": "ssi",
        "name": "SSI",
        "emoji": "🔷",
        "category": "securities",
        "url": "https://www.ssi.com.vn/quan-he-nha-dau-tu/cong-bo-thong-tin",
        "bctc_page": "https://www.ssi.com.vn/quan-he-nha-dau-tu/bao-cao-tai-chinh",
        "source_page": "https://www.ssi.com.vn/quan-he-nha-dau-tu/cong-bo-thong-tin",
    },
    {
        "id": "bvsc",
        "name": "BVSC",
        "emoji": "🛡️",
        "category": "securities",
        "api_url": "https://www.bvsc.com.vn/getPaginateCBTT_V2",
        "params": {
            "pagesizes": 10,
            "currentPage": 1,
            "language": "vi",
        },
        "source_page": "https://www.bvsc.com.vn/danhmuc/quan-he-nha-dau-tu/cong-bo-thong-tin/",
        "bctc_page": "https://www.bvsc.com.vn/danhmuc/quan-he-nha-dau-tu/bao-cao-tai-chinh/",
    },
    {
        "id": "vix",
        "name": "VIX Securities",
        "emoji": "🔶",
        "category": "securities",
        "path": "/qhcd/cong-bo-thong-tin",
        "bctc_path": "/bao-cao",
        "params": {"num": 20, "y": -1},
        "source_page": "https://vixs.vn/qhcd/cong-bo-thong-tin?num=20&y=-1",
    },
    {
        "id": "shs",
        "name": "SHS",
        "emoji": "🔹",
        "category": "securities",
        "api_url": "https://shs.com.vn/api/shareholders/info-disclosure",
        "periodic_api_url": "https://shs.com.vn/api/shareholders/periodic-report",
        "codes": ["DINHKY", "BATTHUONG", "KHAC"],
        "periodic_codes": ["TAICHINH"],
        "params": {"pageSize": 10},
        "source_page": "https://shs.com.vn/quan-he-co-dong/bao-cao-dinh-ky/TAICHINH",
    },
    # ── Ngân hàng ─────────────────────────────────────────────────────────────
    {
        "id": "vpbank",
        "name": "VPBank",
        "emoji": "🏦",
        "category": "bank",
        "url": "https://www.vpbank.com.vn/uiux-api/api/document",
        "feeds": [
            {
                "params": {
                    "lang": "vi",
                    "categoryPath": "/quan-he-nha-dau-tu/cong-bo-thong-tin-khac/2020",
                    "pageSize": 10,
                    "pageIndex": 1,
                },
                "label": "CBTT",
            },
            {
                "params": {
                    "lang": "vi",
                    "categoryPath": "/quan-he-nha-dau-tu/bao-cao-tai-chinh",
                    "pageSize": 10,
                    "pageIndex": 1,
                },
                "label": "BCTC",
            },
        ],
        "source_page": "https://www.vpbank.com.vn/quan-he-nha-dau-tu/cong-bo-thong-tin-khac",
    },
    {
        "id": "eximbank",
        "name": "Eximbank",
        "emoji": "💳",
        "category": "bank",
        "url": "https://eximbank.com.vn/thong-tin-khac",
        "source_page": "https://eximbank.com.vn/thong-tin-khac",
    },
    {
        "id": "mbb",
        "name": "MBBank (MBB)",
        "emoji": "🪖",
        "category": "bank",
        "url": "https://www.mbbank.com.vn/Investor/thong-bao-nha-dau-tu/{year}/0//0",
        "bctc_url": "https://www.mbbank.com.vn/Investor/bao-cao-tai-chinh/{year}/0//0",
        "source_page": "https://www.mbbank.com.vn/Investor/thong-bao-nha-dau-tu",
    },
    {
        "id": "hdbank",
        "name": "HDBank (HDB)",
        "emoji": "🔴",
        "category": "bank",
        "feeds": [
            {
                "api_path": "/vi/investors/thong-tin-nha-dau-tu/quan-he-co-dong/cong-bo-thong-tin-thong-tin-khac",
                "page_url": "https://hdbank.com.vn/vi/investor/thong-tin-nha-dau-tu/quan-he-co-dong/cong-bo-thong-tin-thong-tin-khac",
                "label": "CBTT",
            },
            {
                "api_path": "/vi/investors/thong-tin-nha-dau-tu/bao-cao-tai-chinh",
                "page_url": "https://hdbank.com.vn/vi/investor/thong-tin-nha-dau-tu/bao-cao-tai-chinh",
                "label": "BCTC",
            },
        ],
        "source_page": "https://hdbank.com.vn/vi/investor/thong-tin-nha-dau-tu/quan-he-co-dong/cong-bo-thong-tin-thong-tin-khac",
    },
    {
        "id": "lpb",
        "name": "LPBank (LPB)",
        "emoji": "🌿",
        "category": "bank",
        "url": "https://lpbank.com.vn/nha-dau-tu/cong-bo-thong-tin",
        "categories": [
            ("CONG_BO_THONG_TIN", "CBTT"),
            ("BAO_CAO", "BCTC"),
        ],
        "source_page": "https://lpbank.com.vn/nha-dau-tu/cong-bo-thong-tin",
    },
    {
        "id": "sacombank",
        "name": "Sacombank (STB)",
        "emoji": "🟡",
        "category": "bank",
        "api_url": "https://www.sacombank.com.vn/trang-chu/nha-dau-tu/cong-bo-thong-tin/_jcr_content/root/container/container/shareholdernotice.sacom.shnotice.json",
        "financial_api_url": "https://www.sacombank.com.vn/trang-chu/nha-dau-tu/bao-cao/_jcr_content/root/container/container/reportlisting.sacom.reportlisting.financial.json",
        "source_page": "https://www.sacombank.com.vn/trang-chu/nha-dau-tu/cong-bo-thong-tin.html",
    },
    {
        "id": "acb",
        "name": "ACB",
        "emoji": "🔵",
        "category": "bank",
        "api_url": "https://acb.com.vn/api/front/v1/posts",
        "params": {
            "category_id": 656,
            "limit": 20,
        },
        "source_page": "https://acb.com.vn/nha-dau-tu",
    },
    {
        "id": "techcombank",
        "name": "Techcombank (TCB)",
        "emoji": "🟢",
        "category": "bank",
        "source_page": "https://techcombank.com/nha-dau-tu/cong-bo-thong-tin",
        "endpoints": [
            {"cf_slug": "disclosure-khac", "referer": "thong-tin-khac"},
            {"cf_slug": "hoi-dong-quan-tri", "referer": "nghi-quyet-hdqt"},
            {"cf_slug": "tai-lieu-doanh-nghiep", "referer": "tai-lieu-doanh-nghiep"},
            {"cf_slug": "bao-cao-tai-chinh-vas", "referer": "bao-cao-tai-chinh-vas"},
        ],
    },
    {
        "id": "bidv",
        "name": "BIDV",
        "emoji": "🟠",
        "category": "bank",
        "feeds": [
            {
                "url": "https://bidv.com.vn/vn/quan-he-nha-dau-tu/thong-tin-co-dong",
                "label": "CBTT",
            },
            {
                "url": "https://bidv.com.vn/vn/quan-he-nha-dau-tu/bao-cao-va-tai-lieu/",
                "label": "BCTC",
            },
        ],
        "source_page": "https://bidv.com.vn/vn/quan-he-nha-dau-tu/thong-tin-co-dong",
    },
    {
        "id": "tpb",
        "name": "TPBank (TPB)",
        "emoji": "🟣",
        "category": "bank",
        "feeds": [
            {
                "page_url": "https://tpb.vn/nha-dau-tu/thong-bao-co-dong",
                "key": "thong-bao-co-dong",
                "label": "TBCD",
            },
            {
                "page_url": "https://tpb.vn/nha-dau-tu/bao-cao-tai-chinh",
                "key": "bao-cao-tai-chinh",
                "label": "BCTC",
            },
        ],
        "source_page": "https://tpb.vn/nha-dau-tu/thong-bao-co-dong",
    },
    # ── Khác ──────────────────────────────────────────────────────────────────
    {
        "id": "gelex",
        "name": "Gelex",
        "emoji": "⚡",
        "category": "other",
        "url": "https://gelex.vn/wp-json/wp/v2",
        "source_page": "https://gelex.vn/doc-cat/cong-bo-thong-tin-2",
    },
]
